### ISSUE TITLE
No display on bookworm

### ISSUE THREAD

**Issue by zedstarr** [ccadic/sharpikeebo#11]
No display after following the instructions contained herein and referenced in the youtube videos when running bookworm-based Raspberry Pi OS.

I have found this DRM based driver https://github.com/sqfmi/Sharp-Memory-LCD-Kernel-Driver but have not yet tried it...

**Comment by zedstarr** [comment]
Thanks, I started again with a fresh trixie image and got the display working using the repo above and your instructions :-) 

Seems to want to stick to default white-on-black though...

After boot/login using `echo 1 | sudo tee /sys/module/sharp_drm/parameters/mono_invert` will flip to black-on-white but editing the files as described (adding `sharp_drm=mono_invert:1` to `/boot/firmware/cmdline.txt` and `sharp_drm mono_invert=1` to` /etc/modules`) has no effect  

logs show:
`kernel: Unknown kernel command line parameters "sharp_drm=mono_invert:1", will be passed to user space`
and
`systemd-modules-load[287]: Failed to find module 'sharp-drm mono_invert=1'`

Even creating a file `/etc/modules-load.d/sharp_drm.conf` containing `mono_invert=1` has no effect

**Comment by asmagill** [comment]
Is the yellow LED underneath the screen turning on? If so, you need to go back and recheck that you made the appropriate changes to `sharp-drm.dts` because that is GPIO 22, which is *not* used by our Sharp display.

If the LED isn't turning on, make sure that the spi line has been corrected in `/boot/firmware/config.txt` (you may have `dtparam=spi=on` in there twice -- once at the top which may or may not be commented out which is included as part of the default installation, and a second time at the bottom right above the `dtoverlay=sharp-drm` line which was added by `sudo make install` -- both need to be deleted or commented out, and the correct line `dtoverlay=spi0-1cs,cs0_pin=23` put right above the `sharp-drm` line (I'm not as positive about the `nomiso=1` parameter -- the display doesn't use it, but according to the schematics, the rfm95 radio might -- I need to play around some more -- leaving `nomiso=1` out won't cause a problem, it will just mark a gpio pin as in use that might have been free otherwise.)

Finally, I'd check to make sure the `/boot/firmware/cmdline.txt` file ends with ` fbcon=font:VGA8x8 fbcon=map:10`

**Comment by asmagill** [comment]
Fwiw, using a continuity tester, I can confirm that the radio module we have is only using the Pi's TX and RX pins -- no SPI pins are connected (though they are broken out to the pads on the right of the radio module when looking at the SharpiKeebo's back). So, including `nomiso=1` in the spi overlay will free up a pin for other uses (it's broken out in the pads on the board underneath the Pi header) if you want it.

**Comment by talmage** [comment]
How do I fix this error that occurs when I compile the sharp-drm-driver?

`ERROR: modpost: "drm_fbdev_ttm_setup" [/home/talmage/git/sharp-drm-driver/sharp-drm.ko] undefined!`

Installing `libdrm-dev` didn't fix the problem.

For reference, I'm using Raspian Trixie Lite (unless one of the `apt upgrade`s changed it).

`uname -a` reports `Linux sharpikeebo 6.12.47+rpt-rpi-v7 #1 SMP Raspbian 1:6.12.47-1+rpt1 (2025-09-16) armv7l GNU/Linux`

**Comment by asmagill** [comment]
Look like you're using the 32bit version of Trixie? Haven't tried that yet -- I'm using the 64bit one.

I'll try to give the 32bit version a shot tonight, unless someone else has already figured it out?

**Comment by asmagill** [comment]
You could try https://github.com/ardangelo/sharp-drm-driver -- the repo I give above is forked from it, and the main change was to migrate from `drm_fbdev_generic_setup` to `drm_fbdev_ttm_setup`... maybe the 32bit kernel is lagging the API change?

At any rate, I'll let you know if I figure something out tonight.

**Comment by talmage** [comment]
> Look like you're using the 32bit version of Trixie? Haven't tried that yet -- I'm using the 64bit one.
> 

That's right.  I started this adventure on a Pi Zero and I'm using the same SD card to boot my Pi Zero 2.  I'll try the 64-bit version of Trixie.  I'm fine with that.

**Comment by talmage** [comment]
> ... I'm fine with that.

I'm also an idiot.  I fried my Pi Zero 2 W while setting up 64-bit Trixie.  It will be a week or so before the replacement arrives.

**Comment by talmage** [comment]
Still no output on the Sharp display.  I wonder if this excerpt from `journactl` output is relevant. There's a failure related to spi0.0.


```
Sep 04 17:32:23 sharpikeebo kernel: sharp_memory: entering sharp_memory_probe
Sep 04 17:32:23 sharpikeebo kernel: sharp_memory: entering drm_probe
Sep 04 17:32:23 sharpikeebo kernel: sharp_memory: registering DRM device
Sep 04 17:32:23 sharpikeebo kernel: [drm] Initialized sharp_drm 1.1.0 for spi0.0 on minor 0
Sep 04 17:32:24 sharpikeebo kernel: sharp_memory: entering sharp_memory_pipe_enable
Sep 04 17:32:24 sharpikeebo kernel: sharp_memory: completed sharp_memory_pipe_enable
...
Sep 04 17:32:25 sharpikeebo kernel: sharp-drm spi0.0: [drm] fb1: sharp_drmdrmfb frame buffer device
Sep 04 17:32:25 sharpikeebo kernel: sharp_memory: successful probe
Sep 04 17:32:25 sharpikeebo kernel: sharp_memory: successful probe
Sep 04 17:32:26 sharpikeebo (udev-worker)[364]: spi0.0: Process '/usr/lib/raspberrypi-sys-mods/i2cprobe' failed with exit code 1.
Sep 04 17:32:26 sharpikeebo (udev-worker)[364]: spi0.0: Process '/usr/lib/raspberrypi-sys-mods/i2cprobe' failed with exit code 1.
```
